# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - main
  paths:
    include:
      -backend/**

pool:
  vmImage: ubuntu-latest

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'esmee-test'
      scannerMode: 'Other'
      extraProperties: |
        # Additional properties that will be passed to the scanner,
        # Put one key=value per line, example:
        # sonar.exclusions=**/*.bin
        sonar.projectKey=esmee-test_Tealpanda
        sonar.projectName=Tealpanda
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    sqAnalysisEnabled: true
    codeCoverageTool: JaCoCo
    isJacocoCoverageReportXML: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
