# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend/**

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '7d68e855-6212-4972-871a-9d3ea87125a0'

  # Web app name
  webAppName: 'tealpanda-backend'

  # Environment name
  environmentName: 'tealpanda-backend'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'esmee-test'
        scannerMode: 'Other'
        extraProperties: |
          # Additional properties that will be passed to the scanner,
          # Put one key = value per line, example:
          # sonar.exclusions: **/*.bin
          sonar.projectKey=esmee-test_Tealpanda
          sonar.projectName=Tealpanda

    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'backend/pom.xml'
        publishJUnitResults: true
        sqAnalysisEnabled: true
        codeCoverageToolOption: JaCoCo
        isJacocoCoverageReportXML: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: tealpanda-backend'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
